import requests

res = requests.post("https://cg-3f3ab907.gaojidata.com/api/v1/employee-user/add", headers={"Authorization":"dnqqyW-pYjvma-PkT83Hn5AMf9aEf6Hb70_GM_ExZ2Q="}
,json={"creator": "chenglong.yu",
"productCode": "ubi",
"univCode": "RC00562",
"remark": ""})
print(res.json())


def get_all_ranks(dictionary) -> dict:
    """获取所有键的排名信息"""
    result = {}
    for key, value in dictionary.items():
        result[key] = {
            'rank': value.get('rank'),
            'rankComp': value.get('rankComp')
        }
    return result

x= [{'id': '16254', 'name': '诺奖菲奖校友折合数', 'code': 'arind1', 'editable': 'detail', 'detailDefId': 1263,
     'isRank': True, 'isSim': True, 'indData': {'indValId': 0, 'value': 0,
                                                'effSrc': '诺贝尔奖官网（https://www.nobelprize.org/）；菲尔兹奖官网（https://www.mathunion.org/）',
                                                'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '318+',
                                                'rankAll': '318+', 'RankKind': '', 'rankNgov': '0+', 'maxVal': 39.2,
                                                'score': None, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16266', 'name': '诺贝尔奖校友折合数', 'code': 'ind115', 'editable': '', 'detailDefId': 1263,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 0, 'value': 0, 'effSrc': '诺贝尔奖官网（https://www.nobelprize.org/）',
                 'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '306+', 'rankAll': '306+', 'RankKind': '',
                 'rankNgov': '0+', 'maxVal': 34.6, 'score': None, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16267', 'name': '菲尔兹奖校友折合数', 'code': 'ind116', 'editable': '', 'detailDefId': 1263,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 0, 'value': 0, 'effSrc': '菲尔兹奖官网（https://www.mathunion.org/）',
                 'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '50+', 'rankAll': '50+', 'RankKind': '',
                 'rankNgov': '0+', 'maxVal': 4.9, 'score': None, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16255', 'name': '诺奖菲奖教师折合数', 'code': 'arind2', 'editable': 'detail', 'detailDefId': 1258,
     'isRank': True, 'isSim': True, 'indData': {'indValId': 0, 'value': 0,
                                                'effSrc': '诺贝尔奖官网（https://www.nobelprize.org/）；菲尔兹奖官网（https://www.mathunion.org/）',
                                                'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '160+',
                                                'rankAll': '160+', 'RankKind': '', 'rankNgov': '0+',
                                                'maxVal': 12.27499999, 'score': None, 'accurateScore': None,
                                                'pencentScore': ''}},
    {'id': '16268', 'name': '诺贝尔奖教师折合数', 'code': 'ind106', 'editable': '', 'detailDefId': 1258,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 0, 'value': 0, 'effSrc': '诺贝尔奖官网（https://www.nobelprize.org/）',
                 'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '155+', 'rankAll': '155+', 'RankKind': '',
                 'rankNgov': '0+', 'maxVal': 9.75555556, 'score': None, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16269', 'name': '菲尔兹奖教师折合数', 'code': 'ind107', 'editable': '', 'detailDefId': 1258,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 0, 'value': 0, 'effSrc': '菲尔兹奖官网（https://www.mathunion.org/）',
                 'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '31+', 'rankAll': '31+', 'RankKind': '',
                 'rankNgov': '0+', 'maxVal': 5.93181818, 'score': None, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16256', 'name': '高被引科学家', 'code': 'arind3', 'editable': 'detail', 'detailDefId': 399, 'isRank': True,
     'isSim': True,
     'indData': {'indValId': 5460445, 'value': 33, 'effSrc': '科睿唯安官网', 'effectVer': '2024', 'ranking': '',
                 'rankTyp': '32', 'rankAll': '32', 'RankKind': '', 'rankNgov': '32', 'maxVal': 231, 'score': 37.7964473,
                 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16257', 'name': 'Nature和Science论文折合数', 'code': 'arind4', 'editable': 'detail', 'detailDefId': 1284,
     'isRank': True, 'isSim': True,
     'indData': {'indValId': 5461247, 'value': 51.15, 'effSrc': '科睿唯安官网', 'effectVer': '2020-2024', 'ranking': '',
                 'rankTyp': '46', 'rankAll': '46', 'RankKind': '', 'rankNgov': '46', 'maxVal': 467.3,
                 'score': 33.08452688, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16270', 'name': 'Nature论文', 'code': 'indnature', 'editable': '', 'detailDefId': 1284, 'isRank': False,
     'isSim': True,
     'indData': {'indValId': 5485976, 'value': 28.95, 'effSrc': '科睿唯安官网', 'effectVer': '2020-2024', 'ranking': '',
                 'rankTyp': '52', 'rankAll': '52', 'RankKind': '', 'rankNgov': '52', 'maxVal': 311.8,
                 'score': 30.47096642, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16271', 'name': 'Science论文', 'code': 'indscience', 'editable': '', 'detailDefId': 1284, 'isRank': False,
     'isSim': True,
     'indData': {'indValId': 5487678, 'value': 22.2, 'effSrc': '科睿唯安官网', 'effectVer': '2020-2024', 'ranking': '',
                 'rankTyp': '42', 'rankAll': '42', 'RankKind': '', 'rankNgov': '42', 'maxVal': 155.5,
                 'score': 37.78429215, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16258', 'name': '国际论文折合数', 'code': 'arind5', 'editable': 'val', 'detailDefId': 0, 'isRank': True,
     'isSim': True,
     'indData': {'indValId': 5463111, 'value': 21416, 'effSrc': 'Web of Science官网（http://www.webofscience.com/）',
                 'effectVer': '2024', 'ranking': '', 'rankTyp': '2', 'rankAll': '2', 'RankKind': '', 'rankNgov': '2',
                 'maxVal': 22380, 'score': 97.82258567, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16424', 'name': 'SCIE论文', 'code': 'ind230', 'editable': '', 'detailDefId': 0, 'isRank': False,
     'isSim': False, 'indData': {'indValId': 5477621, 'value': 20020,
                                 'effSrc': '原始数据来源于Web of Science官网。此数值是由软科世界大学学术排名的“国际论文”（PUB）得分重新计算的。',
                                 'effectVer': '2024', 'ranking': '', 'rankTyp': '2', 'rankAll': '2', 'RankKind': '',
                                 'rankNgov': '2', 'maxVal': 20463, 'score': 98.91163584, 'accurateScore': None,
                                 'pencentScore': ''}},
    {'id': '16425', 'name': 'SSCI论文', 'code': 'ind231', 'editable': '', 'detailDefId': 0, 'isRank': False,
     'isSim': False, 'indData': {'indValId': 5480406, 'value': 1049,
                                 'effSrc': '原始数据来源于Web of Science官网。此数值是由软科世界大学学术排名的“国际论文”（PUB）得分重新计算的。',
                                 'effectVer': '2024', 'ranking': '', 'rankTyp': '52', 'rankAll': '52', 'RankKind': '',
                                 'rankNgov': '52', 'maxVal': 2914, 'score': 59.99885609, 'accurateScore': None,
                                 'pencentScore': ''}},
    {'id': '16426', 'name': '被SCIE或SSCI收录的论文数', 'code': 'ind232', 'editable': '', 'detailDefId': 0,
     'isRank': False, 'isSim': False, 'indData': {'indValId': 5483191, 'value': 20601,
                                                  'effSrc': '原始数据来源于Web of Science官网。此数值是由软科世界大学学术排名的“国际论文”（PUB）得分重新计算的。',
                                                  'effectVer': '2024', 'ranking': '', 'rankTyp': '2', 'rankAll': '2',
                                                  'RankKind': '', 'rankNgov': '2', 'maxVal': 21275,
                                                  'score': 98.40323287, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16265', 'name': '师均表现综合得分', 'code': 'pcp', 'editable': '', 'detailDefId': 0, 'isRank': True,
     'isSim': True, 'indData': {'indValId': 5489055, 'value': 6.01313513,
                                'effSrc': '参考指标“校友获奖”、“教师获奖”、“高被引学者”、“N&S论文”、“国际论文”和“全时教师数”',
                                'effectVer': '2024', 'ranking': '', 'rankTyp': '105', 'rankAll': '0', 'RankKind': '',
                                'rankNgov': '0', 'maxVal': 75.01499002, 'score': 28.31238491, 'accurateScore': None,
                                'pencentScore': ''}},
    {'id': '16259', 'name': '诺奖菲奖校友折合数（师均）', 'code': 'arind6', 'editable': '', 'detailDefId': 0,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 5465893, 'value': 0, 'effSrc': '参考指标“诺奖菲奖校友折合数”和“全时教师数”',
                 'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '318+', 'rankAll': '0+', 'RankKind': '',
                 'rankNgov': '0+', 'maxVal': 0.03807947, 'score': 0, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16260', 'name': '诺奖菲奖教师折合数（师均）', 'code': 'arind7', 'editable': '', 'detailDefId': 0,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 5468678, 'value': 0, 'effSrc': '参考指标“诺奖菲奖教师折合数”和“全时教师数”',
                 'effectVer': '1901-2025', 'ranking': '', 'rankTyp': '160+', 'rankAll': '0+', 'RankKind': '',
                 'rankNgov': '0+', 'maxVal': 0.01567329, 'score': 0, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16261', 'name': '高被引科学家（师均）', 'code': 'arind8', 'editable': '', 'detailDefId': 0, 'isRank': False,
     'isSim': True,
     'indData': {'indValId': 5471463, 'value': 0.00820487, 'effSrc': '参考指标“高被引科学家”和“全时教师数”',
                 'effectVer': '2024', 'ranking': '', 'rankTyp': '138', 'rankAll': '138', 'RankKind': '',
                 'rankNgov': '138', 'maxVal': 0.14224138, 'score': 24.0172276, 'accurateScore': None,
                 'pencentScore': ''}},
    {'id': '16262', 'name': 'Nature和Science论文折合数（师均）', 'code': 'arind9', 'editable': '', 'detailDefId': 0,
     'isRank': False, 'isSim': True, 'indData': {'indValId': 5474248, 'value': 0.01271755,
                                                 'effSrc': '参考指标“Nature和Science论文折合数”和“全时教师数”',
                                                 'effectVer': '2020-2024', 'ranking': '', 'rankTyp': '185',
                                                 'rankAll': '185', 'RankKind': '', 'rankNgov': '185',
                                                 'maxVal': 0.53344371, 'score': 15.4403602, 'accurateScore': None,
                                                 'pencentScore': ''}},
    {'id': '16263', 'name': '国际论文折合数（师均）', 'code': 'arind10', 'editable': '', 'detailDefId': 0,
     'isRank': False, 'isSim': True,
     'indData': {'indValId': 5454700, 'value': 5.32471407, 'effSrc': '参考指标“SCIE论文”、“SSCI论文”和“全时教师数”',
                 'effectVer': '2024', 'ranking': '', 'rankTyp': '59', 'rankAll': '59', 'RankKind': '', 'rankNgov': '59',
                 'maxVal': 12.91748768, 'score': 64.20356119, 'accurateScore': None, 'pencentScore': ''}},
    {'id': '16264', 'name': '全时教师数', 'code': 'arind11', 'editable': 'val', 'detailDefId': 0, 'isRank': False,
     'isSim': True,
     'indData': {'indValId': 5457485, 'value': 4022, 'effSrc': '《本科教学质量报告》', 'effectVer': '2024', 'ranking': '',
                 'rankTyp': '13', 'rankAll': '13', 'RankKind': '', 'rankNgov': '13', 'maxVal': 5291,
                 'score': 87.18708391, 'accurateScore': None, 'pencentScore': ''}}]


z = {'code': 200, 'message': 'success',
     'data': {'univ': {'score': 36.6, 'rank': '31', 'rankAll': '', 'rankNgov': '', 'ordNo': 0, 'maxOrdNo': 0},
              'inds': {'16254': {'val': 0, 'rank': '318+', 'score': 0, 'finalScore': 0},
                       '16255': {'val': 0, 'rank': '160+', 'score': 0, 'finalScore': 0},
                       '16256': {'val': 33, 'rank': '32', 'score': 0, 'finalScore': 7.55928946},
                       '16257': {'val': 51.15, 'rank': '46', 'score': 0, 'finalScore': 6.61690538},
                       '16258': {'val': 21416, 'rank': '2', 'score': 0, 'finalScore': 19.56451713},
                       '16259': {'val': 0, 'rank': '318+', 'score': 0, 'finalScore': 0},
                       '16260': {'val': 0, 'rank': '160+', 'score': 0, 'finalScore': 0},
                       '16261': {'val': 0.00820487, 'rank': '138', 'score': 0, 'finalScore': 0},
                       '16262': {'val': 0.01271755, 'rank': '185', 'score': 0, 'finalScore': 0},
                       '16263': {'val': 5.32471407, 'rank': '59', 'score': 0, 'finalScore': 0},
                       '16264': {'val': 4022, 'rank': '13', 'score': 0, 'finalScore': 0},
                       '16265': {'val': 6.01313513, 'rank': '105', 'score': 0, 'finalScore': 2.83123849},
                       '16266': {'val': 0, 'rank': '306+', 'score': 0, 'finalScore': 0},
                       '16267': {'val': 0, 'rank': '50+', 'score': 0, 'finalScore': 0},
                       '16268': {'val': 0, 'rank': '155+', 'score': 0, 'finalScore': 0},
                       '16269': {'val': 0, 'rank': '31+', 'score': 0, 'finalScore': 0},
                       '16270': {'val': 28.95, 'rank': '52', 'score': 0, 'finalScore': 0},
                       '16271': {'val': 22.2, 'rank': '42', 'score': 0, 'finalScore': 0},
                       '16424': {'val': 20020, 'rank': '2', 'score': 0, 'finalScore': 0},
                       '16425': {'val': 1049, 'rank': '52', 'score': 0, 'finalScore': 0},
                       '16426': {'val': 20601, 'rank': '2', 'score': 0, 'finalScore': 0}}}}
